if(NOT EXISTS "${MAP}")
    message(FATAL_ERROR "Data-only native test requires an actual linker map: ${MAP}")
endif()
file(READ "${MAP}" LINK_MAP)
foreach(MODULE IN ITEMS Runtime Nodes GeometryData ShaderMaterial)
    if(NOT LINK_MAP MATCHES "LiteLayer:${MODULE}\\.cpp\\.obj")
        message(FATAL_ERROR "Data-only link did not execute its ${MODULE} implementation.")
    endif()
endforeach()
foreach(MODULE IN ITEMS Engine Geometry ShaderPipeline Texture RenderOrder Audio)
    if(LINK_MAP MATCHES "LiteLayer:${MODULE}\\.cpp\\.obj")
        message(FATAL_ERROR "Data-only consumer unexpectedly linked ${MODULE}.")
    endif()
endforeach()
if(LINK_MAP MATCHES "bgfx:|LiteShaderCompiler|AppRuntime|js_native_api|napi_")
    message(FATAL_ERROR "Data-only consumer linked rendering/compiler/VM implementation.")
endif()
message(STATUS "Data-only link: four CPU modules, no rendering/compiler/VM implementation.")
