# Function scope prevents optional dependency settings from changing unrelated
# BabylonNative dependencies or the parent's install/shared-library policy.
function(babylon_lite_make_ui_dependencies)
    set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
    set(FT_DISABLE_ZLIB ON)
    set(FT_DISABLE_BZIP2 ON)
    set(FT_DISABLE_PNG ON)
    set(FT_DISABLE_HARFBUZZ ON)
    set(FT_DISABLE_BROTLI ON)
    set(SKIP_INSTALL_ALL ON)
    set(BUILD_SHARED_LIBS OFF)
    FetchContent_MakeAvailable_With_Message(LiteFreetype)
    if(NOT TARGET Freetype::Freetype)
        add_library(Freetype::Freetype ALIAS freetype)
    endif()

    set(RMLUI_FONT_ENGINE freetype)
    set(RMLUI_SAMPLES OFF)
    set(RMLUI_TESTS OFF)
    set(RMLUI_LUA_BINDINGS OFF)
    set(RMLUI_LOTTIE_PLUGIN OFF)
    set(RMLUI_SVG_PLUGIN OFF)
    set(RMLUI_THIRDPARTY_CONTAINERS ON)
    set(RMLUI_PRECOMPILED_HEADERS OFF)
    set(RMLUI_MATRIX_ROW_MAJOR OFF)
    set(RMLUI_WARNINGS_AS_ERRORS OFF)
    FetchContent_MakeAvailable_With_Message(RmlUi)
    FetchContent_GetProperties(RmlUi SOURCE_DIR _rmlui_source)
    include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/RmlUi/ApplyBoxShadowPatch.cmake")
    babylon_lite_patch_rmlui("${_rmlui_source}")
    foreach(_rml_target IN ITEMS rmlui_core rmlui_debugger freetype)
        if(TARGET ${_rml_target})
            set_property(TARGET ${_rml_target} PROPERTY FOLDER Dependencies/RmlUi)
        endif()
    endforeach()
    set(RmlUi_SOURCE_DIR "${_rmlui_source}" PARENT_SCOPE)
endfunction()

babylon_lite_make_ui_dependencies()
